version: "3"
services:
  first_server:
    build:
      context: ./first_server
    depends_on:
      - sql_server
    networks:
      - my_network
    ports:
      - 8080:80

  second_server:
    build:
      context: ./second_server
    depends_on:
      - first_server
    networks:
      - my_network
    ports:
      - 8081:80

  sql_server:
    image: mysql:latest
    command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /entrypoint.sh mysqld
          "
    volumes:
      - ./sql_server/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql_server/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: your_password

networks:
  my_network:
