version: '3'
services:
  php56-example1:
    build:
      context: ./example1
      dockerfile: Dockerfile
    container_name: php56-example1
    networks:
      - mynetwork
    ports:
      - 8080:80

  php56-example2:
    build:
      context: ./example2
      dockerfile: Dockerfile
    container_name: php56-example2
    networks:
      - mynetwork
    ports:
      - 8081:80

  php56-example3:
    build:
      context: ./example3
      dockerfile: Dockerfile
    container_name: php56-example3
    networks:
      - mynetwork
    ports:
      - 8082:80

networks:
  mynetwork:
    driver: bridge
