version: '3'
services:
  app:
    build:
      context: ./App
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - DB_HOST=db
      - DB_PORT=80

  db:
    build:
      context: ./Db
      dockerfile: Dockerfile
    ports:
      - 8081:80
